name: CratesPlus
description: ${project.description}
main: plus.crates.CratesPlus
version: ${project.version}
author: ShaneTheDarkLord
softdepend: [HolographicDisplays , IndividualHolograms , Multiverse-Core]
commands:
  crate:
    description: Main CratesPlus command
    aliases: [cratesplus, crates, cp, complexcrates, kc, koffeecrates]
permissions:
  cratesplus.admin:
    default: op
  cratesplus.givekey:
    default: op
  cratesplus.updates:
    default: op