name: CratesPlus
description: ${project.description}
main: plus.crates.CratesPlus
version: ${project.version}
author: ShaneTheDarkLord
softdepend: [HolographicDisplays,IndividualHolograms]
commands:
  crate:
    description: Main CratesPlus command
    aliases: [cratesplus, crates, cp, complexcrates]
permissions:
  cratesplus.admin:
    default: op
  cratesplus.updates:
    default: op